project_id = "zaaiorcdjhvkckbktiii"

[functions.scrape-egw-book]
verify_jwt = true

[functions.debug-toc]
verify_jwt = true

[functions.find-paragraph-matches]
verify_jwt = true

[functions.import-manual-version]
verify_jwt = true
